version: '2'
services:
    dataqualitybooster-app:
        image: dataqualitybooster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://dataqualitybooster-postgresql:5432/dataQualityBooster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=dataqualitybooster-elasticsearch:9300
        ports:
            - 8080:8080
    dataqualitybooster-postgresql:
        extends:
            file: postgresql.yml
            service: dataqualitybooster-postgresql
    dataqualitybooster-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: dataqualitybooster-elasticsearch
